const drugs = [

{
  name:"Semaglutide", brand:"Wegovy",
  approval:"long", route:"injectable", tags:["glp1"],
  wl:16,
  mechShort:"GLP-1 receptor agonist",
  dose:"Start 0.25 mg SC weekly → 0.5 → 1.0 → 1.7 → 2.4 mg weekly (target). Titrate every 4 weeks. Slower titration if GI intolerance.",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Approved ≥12 yrs.",
  contraindications:["Personal/family hx medullary thyroid cancer (MTC)","MEN 2 syndrome","Hypersensitivity to semaglutide"],
  preScreen:["Personal/family hx of thyroid cancer or MEN 2","History of pancreatitis","Gallbladder disease history","Renal function (caution with dehydration)","Diabetic retinopathy evaluation if applicable","Pregnancy test","Screen for depression/suicidal ideation baseline","Current GLP-1 agonist use (do not combine)"],
  sideEffects:["Nausea, vomiting (most common — dose-related)","Diarrhea or constipation","Abdominal pain, dyspepsia","Fatigue, dizziness, headache","Increased heart rate","Elevated lipase","Delayed gastric emptying"],
  warnings:["BLACK BOX: thyroid C-cell tumors in rodents — unknown if applies to humans","Pancreatitis — discontinue if suspected, do not restart if confirmed","Cholelithiasis and cholecystitis","Hypoglycemia risk when combined with sulfonylurea or insulin","Acute kidney injury with dehydration from GI side effects","Monitor for depression and suicidal ideation","Worsening of diabetic retinopathy — ophthalmology eval if retinopathy present"],
  interactions:["Delayed gastric emptying may affect absorption of oral medications","Do not combine with other GLP-1 agonists","Reduce insulin or sulfonylurea doses to prevent hypoglycemia"],
  monitoring:["Weight and BMI each visit","Blood pressure and HR","Renal function if severe GI side effects / dehydration","Lipase if pancreatitis suspected","Ophthalmology if diabetic retinopathy","Mental health screening","4-week titration schedule"],
  specialNotes:"Only AOM with a formal FDA cardiovascular risk-reduction indication in adults with established CVD and overweight/obesity (added March 8, 2024). In SELECT, MACE fell from 8.0% to 6.5% over the trial period. Approved ≥12 years. Do not use for T2DM at 2.4 mg dose — separate semaglutide products exist for that indication."
},
{
  name:"Tirzepatide", brand:"Zepbound",
  approval:"long", route:"injectable", tags:["glp1"],
  wl:22,
  mechShort:"Dual GLP-1 + GIP receptor agonist",
  dose:"Start 2.5 mg SC weekly → 5 → 7.5 → 10 → 12.5 → 15 mg weekly. Titrate every 4 weeks. Target: 5–15 mg. Slower titration if GI intolerance.",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Also FDA-approved for obstructive sleep apnea and T2DM at same doses.",
  contraindications:["Personal/family hx medullary thyroid cancer (MTC)","MEN 2 syndrome","Hypersensitivity to tirzepatide"],
  preScreen:["Thyroid cancer / MEN 2 personal or family history","History of pancreatitis","Gallbladder disease history","Renal function baseline","Pregnancy test","Screen for depression/SI baseline","Current GLP-1 agonist use (do not combine)","Current insulin or SU use (hypoglycemia risk)"],
  sideEffects:["Nausea, diarrhea, vomiting, constipation (most common)","Abdominal pain, dyspepsia","Injection site reactions","Fatigue, dizziness","Hair loss (telogen effluvium)","GERD, flatulence, abdominal distension","Hypotension","Eructation"],
  warnings:["BLACK BOX: thyroid C-cell tumors in rodents","Pancreatitis — discontinue if suspected","Cholelithiasis / cholecystitis","Hypoglycemia risk with sulfonylureas or insulin","Acute kidney injury with GI-related dehydration","Monitor for depression and suicidal ideation","Pulmonary aspiration risk during general anesthesia or deep sedation","Do not use with other GLP-1 agonists"],
  interactions:["Delayed gastric emptying → affects absorption of oral medications","Reduce insulin or SU doses to avoid hypoglycemia","Do not combine with other GLP-1 agonists"],
  monitoring:["Weight and BMI each visit","HR and blood pressure","Renal function if GI side effects severe","Lipase if pancreatitis symptoms","Mental health screening"],
  specialNotes:"Highest average weight loss of any currently approved AOM (~22–23%). FDA approved tirzepatide for moderate to severe obstructive sleep apnea in adults with obesity on December 20, 2024, making it the first drug with an OSA indication in this population. Generally better tolerated than other GLP-1 RAs per clinical studies."
},
{
  name:"Liraglutide", brand:"Saxenda",
  approval:"long", route:"injectable", tags:["glp1"],
  wl:8,
  mechShort:"GLP-1 receptor agonist (daily injection)",
  dose:"Start 0.6 mg SC daily → 1.2 → 1.8 → 2.4 → 3.0 mg daily. Titrate every 7 days. Target: 3.0 mg. Slower titration permitted for tolerability.",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Approved ≥12 yrs.",
  contraindications:["Personal/family hx medullary thyroid cancer (MTC)","MEN 2 syndrome","Hypersensitivity to liraglutide"],
  preScreen:["Thyroid cancer / MEN 2 personal or family history","History of pancreatitis","Gallbladder disease","Renal function baseline","Pregnancy test","Depression/SI baseline screen","Current GLP-1 agonist (do not combine)","Evaluate: if <4% weight loss at 16 weeks → discontinue"],
  sideEffects:["Nausea, vomiting (most common early — dose-related)","Diarrhea or constipation","Bloating, fullness, dyspepsia","Headache, fatigue, dizziness","Abdominal pain","Increased heart rate","Elevated lipase","Delayed gastric emptying"],
  warnings:["BLACK BOX: thyroid C-cell tumors in rodents","Pancreatitis — discontinue promptly if suspected","Cholelithiasis and cholecystitis","Hypoglycemia with insulin, sulfonylureas, TZDs, meglitinides","Worsening renal function with dehydration","Monitor for depression and suicidal ideation","Low CYP450 interaction potential"],
  interactions:["Delays gastric emptying — may affect timing-sensitive oral medications","Enhances hypoglycemic effects of insulin, SUs, TZDs","Do not combine with other GLP-1 agonists"],
  monitoring:["Weight at each visit","4% weight loss threshold check at 16 weeks — discontinue if not met","HR and BP","Renal function if dehydration risk","Lipase if GI symptoms suggest pancreatitis","Mental health screening"],
  specialNotes:"Daily injection is a disadvantage vs weekly alternatives. Approved ≥12 years. Note: 1.8 mg dose is a separate product (Victoza) approved for T2DM and CV risk reduction in T2DM — different indication from 3.0 mg obesity dose."
},
{
  name:"Phentermine / Topiramate ER", brand:"Qsymia",
  approval:"long", route:"oral", tags:["schedule"],
  wl:10,
  mechShort:"Sympathomimetic amine + carbonic anhydrase inhibitor / neurostabilizer",
  dose:"Start 3.75/23 mg daily (AM) × 14 days → 7.5/46 mg (recommended dose). If <3% weight loss at 12 weeks → escalate to 11.25/69 mg × 14 days → 15/92 mg. If <5% weight loss at 12 weeks on max dose → discontinue. Taper from max dose — do not abruptly stop (seizure risk from topiramate).",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Approved ≥12 yrs. DEA Schedule IV.",
  contraindications:["Pregnancy — teratogen (orofacial clefts)","Glaucoma","Uncontrolled hyperthyroidism","Within 14 days of MAO inhibitor","Hypersensitivity to sympathomimetic amines","Cardiovascular disease (CAD, stroke, arrhythmia, CHF, uncontrolled HTN)"],
  preScreen:["PREGNANCY TEST required before starting — monthly thereafter","Contraception counseling (REMS program — optional but recommended)","Screen for glaucoma history","Thyroid function","Cardiac history and EKG if indicated","Anxiety disorder or bipolar disorder history (phentermine component)","Renal function (max dose 7.5/46 mg if moderate renal impairment)","Hepatic function (dose limit at moderate hepatic impairment)","Baseline heart rate","History of kidney stones (topiramate increases risk)","Current opioid or CNS depressant use","History of seizures"],
  sideEffects:["Paresthesia (tingling in extremities) — very common from topiramate","Dizziness, dysgeusia (taste distortion)","Dry mouth, constipation, insomnia","Sympathomimetic effects: elevated BP, increased HR, tremor, restlessness","Cognitive impairment / word-finding difficulty (topiramate — 'dopamax' effect)","Metabolic acidosis (topiramate)"],
  warnings:["Teratogenic — orofacial clefts. Monthly pregnancy tests required during treatment","Acute myopia and secondary angle closure glaucoma — discontinue if occurs","Increased heart rate — monitor at each visit","Metabolic acidosis (check bicarbonate)","Suicidal ideation — monitor","Mood and sleep disorders","Cognitive impairment — caution with driving and operating machinery","Hypokalemia with non-potassium-sparing diuretics","Oligohidrosis and hyperthermia (decreased sweating — more common in pediatric patients)","Kidney stones — topiramate inhibits carbonic anhydrase","Do not abruptly stop from max dose — seizure risk (topiramate)"],
  interactions:["MAO inhibitors — contraindicated (hypertensive crisis)","Avoid alcohol — potentiation of CNS depression","Non-K-sparing diuretics → hypokalemia","May cause irregular menstrual bleeding with OCPs (do not stop OCP — still effective)","Potentiates CNS depressants","Topiramate may increase phenytoin and lithium levels"],
  monitoring:["Monthly pregnancy tests in women of reproductive potential","HR at every visit","Serum bicarbonate, creatinine, potassium (metabolic acidosis, renal)","Glucose in patients on antidiabetic medications","Mental health and mood screening","Assess for cognitive side effects (word-finding, concentration)","Kidney stone symptoms"],
  specialNotes:"REMS program exists — completion is optional before prescribing. Taper from max dose to minimize seizure risk (topiramate effect). Teratogenicity is the most critical safety concern — document contraception at every visit. Consider writing it into your clinic SOP."
},
{
  name:"Naltrexone / Bupropion ER", brand:"Contrave",
  approval:"long", route:"oral", tags:[],
  wl:6,
  mechShort:"Opioid antagonist + dopamine/NE reuptake inhibitor",
  dose:"Week 1: 1 tab AM. Week 2: 1 AM + 1 PM. Week 3: 2 AM + 1 PM. Week 4+: 2 AM + 2 PM. Each tablet = 8 mg naltrexone / 90 mg bupropion. Max: 32 mg naltrexone / 360 mg bupropion daily. Do NOT take with high-fat meal (increases absorption → seizure risk).",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Not DEA scheduled.",
  contraindications:["Uncontrolled hypertension","Seizure disorder or history of seizures","Anorexia nervosa or bulimia (hard contraindication — seizure risk)","Abrupt discontinuation of alcohol, benzodiazepines, barbiturates, or antiepileptics","Chronic opioid use, or opioid use within 7 days","Use of other bupropion-containing products","Within 14 days of MAO inhibitor","Known allergy to any component"],
  preScreen:["Screen for eating disorders — bulimia and AN are HARD contraindications","Current opioid use — must discontinue ≥7 days before starting","Blood pressure — uncontrolled HTN is contraindication","Seizure history (any history is a contraindication)","MAO inhibitor use within 14 days","History of mania or bipolar disorder (bupropion can precipitate manic episode)","Screen for suicidal ideation baseline","Hepatic function (naltrexone — hepatotoxicity risk)","Angle-closure glaucoma risk","Alcohol and benzo use — abrupt discontinuation must be managed first","Review all CYP2D6-metabolized medications (bupropion inhibits CYP2D6)"],
  sideEffects:["Nausea (most common — often early and transient)","Constipation, headache","Vomiting, dizziness","Insomnia, dry mouth","Diarrhea","Elevated blood pressure and heart rate"],
  warnings:["BLACK BOX (bupropion): increased risk of suicidal ideation in children, adolescents, and young adults with psychiatric disorders","Seizure risk — dose-dependent; high-fat meal increases absorption; do not exceed dosing schedule","Bupropion is a potent CYP2D6 inhibitor — affects many drug levels","Psychiatric adverse effects: depression, mania, psychosis, aggression, hostility, SI","Angle-closure glaucoma","Hepatotoxicity (naltrexone component)","False positive urine drug screen for amphetamines","Monitor BP and HR — especially in patients with cardiac or cerebrovascular disease"],
  interactions:["Opioids — naltrexone blocks opioid receptors, can precipitate acute withdrawal; all opioids must be stopped ≥7 days prior","MAO inhibitors — hypertensive crisis (contraindicated)","CYP2D6 substrates — bupropion raises their levels: SSRIs, TCAs, antipsychotics (haloperidol, risperidone, thioridazine, clozapine, olanzapine), metoprolol, propafenone, flecainide","CYP2B6 inhibitors/inducers affect bupropion levels (unclear clinical consequence)","Levodopa/amantadine — CNS toxicity risk","Digoxin levels may decrease","Drugs that lower seizure threshold — use with extreme caution"],
  monitoring:["BP and HR at each visit","Mental health screening and suicidal ideation at each visit","Hepatic function if hepatotoxicity concern develops","Drug interaction surveillance (CYP2D6)","Urine drug screen awareness (false positive amphetamines)","Mood and psychiatric symptoms"],
  specialNotes:"Pregnancy removed as contraindication in 2020, but recommend discontinuing when pregnancy recognized. The CYP2D6 inhibition from bupropion is highly clinically relevant — always review patient's full medication list. Screen every patient for bulimia (hard seizure-risk contraindication). Good option for patients with comorbid depression, smoking cessation need, or addictive eating behaviors."
},
{
  name:"Phentermine", brand:"Adipex-P, Lomaira",
  approval:"short", route:"oral", tags:["schedule"],
  wl:9,
  mechShort:"Sympathomimetic amine (norepinephrine releaser — appetite suppression)",
  dose:"37.5 mg capsule or tablet once daily (AM) — or split as BID with scored tablet. Short-acting 8 mg tablet available TID before meals. 15 mg and 30 mg ER capsules also available. FDA-approved for 12 weeks only; commonly used long-term off-label in low-CV-risk patients. DEA Schedule IV.",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Short-term (12 wks per FDA). Approved ≥17 yrs.",
  contraindications:["Cardiovascular disease (CAD, stroke, arrhythmias, CHF, uncontrolled HTN)","Within 14 days of MAO inhibitor","Uncontrolled hyperthyroidism","Glaucoma","Agitated states","History of drug abuse","Anxiety disorder or bipolar disorder","Pregnancy or nursing","Hypersensitivity"],
  preScreen:["Detailed cardiac history — any significant CVD is a contraindication","Blood pressure (uncontrolled HTN = contraindication)","Thyroid function (TSH)","Glaucoma history","Substance use disorder history","Psychiatric history — anxiety disorder, bipolar (contraindicated)","Current MAO inhibitor use (within 14 days is contraindicated)","Current SSRI use — serotonin syndrome risk (counsel, not absolute contraindication)","Renal function — 62–85% renally excreted, use caution with impairment","Baseline HR","Full medication review"],
  sideEffects:["Headache, blood pressure elevation, increased HR","Overstimulation, tremor, restlessness","Dry mouth","Constipation, insomnia","Palpitations, tachycardia","Dizziness, dysphoria","Dysgeusia (taste distortion)","Blurred vision"],
  warnings:["Tolerance to anorexigenic effect can develop — do not exceed dose; reconsider plan if tolerance occurs","Chemically related to amphetamines — abuse potential (though psychological dependence is rare in obesity treatment)","Positive on urine drug screens for amphetamines — warn patients","SSRIs + phentermine → serotonin syndrome risk — counsel patients","Valvular heart disease and pulmonary HTN reported with fen-phen combination (attributed to fenfluramine, not phentermine)","DEA Schedule IV controlled substance"],
  interactions:["MAO inhibitors — contraindicated (hypertensive crisis)","Alcohol — adverse interaction","Insulin / oral hypoglycemics — hypoglycemia risk (may need dose reduction)","SSRIs — serotonin syndrome risk (not absolute contraindication but counsel carefully)","Adrenergic neuron blocking drugs — phentermine reduces antihypertensive effect","Possible interaction with some anesthetic agents"],
  monitoring:["BP and HR at every visit","Weight monthly","Mental health and mood assessment","Watch for tolerance developing","Drug screen counseling"],
  specialNotes:"Most widely prescribed AOM historically. Long-term use (>12 weeks) is common in clinical practice and supported by retrospective data and expert opinion, especially in low CV risk patients. Use caution with renal impairment. Inform patients about false-positive drug screens. Consider as monotherapy or in combination (off-label) with topiramate."
},
{
  name:"Orlistat", brand:"Xenical (Rx 120 mg) · Alli (OTC 60 mg)",
  approval:"long", route:"oral", tags:[],
  wl:5,
  mechShort:"Gastrointestinal lipase inhibitor — blocks ~30% of dietary fat absorption",
  dose:"Rx: 120 mg TID with each main fat-containing meal (during or up to 1 hr after meal). OTC: 60 mg TID. No dose titration needed. Take multivitamin daily ≥2 hrs before or after orlistat.",
  indications:"BMI ≥30, or ≥27 with weight-related comorbidity. Approved ≥8 yrs. Only AOM available OTC.",
  contraindications:["Chronic malabsorption syndrome","Cholestasis","Pregnancy"],
  preScreen:["Assess dietary fat intake — GI side effects proportional to fat content of meals","History of malabsorption disorders (contraindicated)","Gallbladder disease history (increased cholelithiasis risk)","Fat-soluble vitamin status (vitamins A, D, E, K)","Warfarin use (vitamin K absorption reduced — monitor INR)","Levothyroxine use (separate dosing by ≥4 hrs)","Cyclosporine use (major interaction — separate by ≥3 hrs)","Antiseizure medication use","Oral contraceptive use","History of kidney stones (oxalate stones)","Renal function if stone risk"],
  sideEffects:["Oily rectal discharge / steatorrhea — most common","Flatus with discharge (can be socially significant)","Fecal urgency and incontinence","Increased defecation frequency","Fat-soluble vitamin deficiency (A, D, E, K) without supplementation"],
  warnings:["GI side effects significantly worsen with high-fat diet (>30% of calories from fat) — patient education is critical","Always prescribe daily multivitamin — take ≥2 hrs apart from orlistat","Rare severe liver injury reported post-marketing","Rare pancreatitis","Increases intestinal oxalate absorption → kidney stones (especially calcium oxalate)","Increases cholelithiasis risk"],
  interactions:["Cyclosporine — give ≥3 hrs apart (orlistat reduces absorption and plasma levels)","Warfarin — reduces vitamin K absorption; monitor INR closely","Levothyroxine — separate dosing by ≥4 hrs","Antiseizure medications — may reduce absorption","Oral contraceptives — may reduce absorption","Beta-carotene and vitamin E supplements — absorption reduced 30–60%"],
  monitoring:["Fat-soluble vitamin levels periodically (especially Vitamin D)","INR if on warfarin (can change significantly)","Thyroid levels if on levothyroxine","Kidney function and urinary oxalate if stone risk","Patient adherence to low-fat diet"],
  specialNotes:"Only AOM working peripherally (no CNS effects). Minimal systemic absorption. Efficacy is entirely diet-dependent — if patient doesn't limit fat, GI side effects are severe and drug appears not to work. OTC version (Alli 60 mg) is readily accessible. Approved from age 8. Good option for patients who cannot or will not use injectable agents and have no malabsorption issues."
},
{
  name:"Diethylpropion", brand:"Tenuate",
  approval:"short", route:"oral", tags:["schedule"],
  wl:7,
  mechShort:"Sympathomimetic amine (appetite suppressant)",
  dose:"25 mg TID (before meals), or 75 mg ER once daily mid-morning. FDA-approved 12 weeks. DEA Schedule IV.",
  indications:"BMI ≥30, or ≥27 with comorbidity. Short-term only. DEA Schedule IV.",
  contraindications:["Advanced arteriosclerosis or cardiovascular disease","Uncontrolled hypertension","Hyperthyroidism","Glaucoma","History of drug abuse","Agitated states","Within 14 days of MAO inhibitor","Pregnancy","Hypersensitivity"],
  preScreen:["Cardiac history and BP","Thyroid function","Glaucoma history","Substance use history","MAO inhibitor use","Anxiety/psychiatric history"],
  sideEffects:["Palpitations, tachycardia, elevated BP","Overstimulation, tremor, restlessness","Insomnia, dry mouth","Dizziness, dysphoria"],
  warnings:["Tolerance can develop","DEA Schedule IV controlled substance","Sympathomimetic class adverse effects"],
  interactions:["MAO inhibitors — contraindicated","Alcohol","Insulin / oral hypoglycemics — hypoglycemia risk"],
  monitoring:["BP and HR","Weight","Mood and affect"],
  specialNotes:"Less commonly used than phentermine in practice. Some data suggest lower abuse potential than phentermine. Schedule IV — same as phentermine."
},
{
  name:"Phendimetrazine", brand:"Bontril",
  approval:"short", route:"oral", tags:["schedule"],
  wl:7,
  mechShort:"Sympathomimetic amine (appetite suppressant)",
  dose:"35 mg TID (30–60 min before meals), or 105 mg ER once daily before AM meal. DEA Schedule III.",
  indications:"Short-term only. BMI ≥30 or ≥27 with comorbidity. DEA Schedule III.",
  contraindications:["Cardiovascular disease, arteriosclerosis","Uncontrolled hypertension","Hyperthyroidism","Glaucoma","Drug abuse history","Agitated states","Within 14 days of MAO inhibitor","Pregnancy","Hypersensitivity"],
  preScreen:["Same pre-screen as other sympathomimetic amines","Note higher DEA scheduling (Schedule III vs phentermine's Schedule IV)"],
  sideEffects:["Palpitations, tachycardia, elevated BP","Overstimulation, insomnia","Dry mouth, dizziness"],
  warnings:["DEA Schedule III — higher scheduling than phentermine","Tolerance can develop","Sympathomimetic class effects"],
  interactions:["MAO inhibitors — contraindicated","Alcohol","Insulin / oral hypoglycemics"],
  monitoring:["BP and HR","Weight","Mood"],
  specialNotes:"DEA Schedule III — more tightly controlled than phentermine (Schedule IV). Rarely used in current practice. Some prescribers prefer it for lower perceived abuse potential despite higher scheduling."
},
{
  name:"Benzphetamine", brand:"Didrex",
  approval:"short", route:"oral", tags:["schedule"],
  wl:7,
  mechShort:"Sympathomimetic amine (appetite suppressant)",
  dose:"25–50 mg once daily to TID. DEA Schedule III.",
  indications:"Short-term only. DEA Schedule III. Not commonly used in practice.",
  contraindications:["Cardiovascular disease","Uncontrolled hypertension","Hyperthyroidism","Glaucoma","Drug abuse history","Agitated states","MAO inhibitors within 14 days","Pregnancy","Hypersensitivity"],
  preScreen:["Same pre-screen as other sympathomimetic amines","Highest scheduling among sympathomimetics"],
  sideEffects:["Palpitations, tachycardia","Overstimulation, insomnia","Dry mouth, tremor"],
  warnings:["DEA Schedule III — highest scheduling among commonly used sympathomimetics","Tolerance can develop"],
  interactions:["MAO inhibitors — contraindicated","Insulin / oral hypoglycemics"],
  monitoring:["BP, HR, weight"],
  specialNotes:"Rarely used in contemporary obesity medicine. DEA Schedule III. Approved age ≥12 years per some references though pediatric use warrants caution."
},
{
  name:"Setmelanotide", brand:"Imcivree",
  approval:"long", route:"injectable", tags:["mono"],
  wl:null,
  mechShort:"Melanocortin-4 receptor (MC4R) agonist",
  dose:"Adults and ≥12 yrs: Start 2 mg SC once daily × 2 weeks. If tolerated → 3 mg daily. If 2 mg not tolerated → reduce to 1 mg daily. Children 6–11 yrs: Start 1 mg daily → if tolerated increase to 2 mg → can increase to 3 mg daily if tolerated.",
  indications:"MONOGENIC OBESITY ONLY: POMC deficiency, PCSK1 deficiency, or LEPR deficiency (confirmed by genetic testing showing pathogenic/likely pathogenic/VUS variants), OR Bardet-Biedl syndrome (can be diagnosed clinically). Age ≥6 yrs. NOT indicated for polygenic/common obesity.",
  contraindications:["Hypersensitivity to setmelanotide or components","Neonates and infants (benzyl alcohol preservative — gasping syndrome risk)","General obesity (polygenic) — will not be effective"],
  preScreen:["Genetic testing to confirm POMC/PCSK1/LEPR variants — required (except Bardet-Biedl)","Bardet-Biedl syndrome: clinical diagnosis acceptable","Full body skin examination before initiating — baseline for nevi and pigmentation","Mental health baseline screen (depression, suicidal ideation)","Screen for sexual arousal adverse effects (especially males)","Renal function (39% excreted unchanged in urine)","Pregnancy test","Pediatric patients: weight and height — monitor growth"],
  sideEffects:["Injection site reactions (≥23% — most common)","Skin hyperpigmentation (generalized — ≥23%)","Nausea, diarrhea, vomiting","Headache, abdominal pain, back pain","Fatigue","Spontaneous penile erection (males)","Depression","Upper respiratory tract infection"],
  warnings:["Spontaneous penile erections — inform male patients; erection >4 hours → seek emergency care","Depression and suicidal ideation — monitor closely; discontinue if suicidal thoughts develop","Generalized skin hyperpigmentation and darkening of pre-existing nevi — full skin exam before and periodically during treatment","Benzyl alcohol preservative — NOT for neonates or infants (gasping syndrome and death risk)"],
  interactions:["Low CYP450 interaction potential","No formal drug-drug interaction studies conducted — use caution"],
  monitoring:["Weight and BMI q4–8 weeks","Full body skin exam and nevi monitoring periodically","Mental health screening and depression assessment","Sexual adverse events (males)","Discontinue if <5% weight loss (or <5% BMI reduction if still growing) after 12–16 weeks","Pediatric patients: growth monitoring"],
  specialNotes:"Entirely different mechanism from all other AOMs — targets the MC4R pathway to restore satiety signaling lost due to genetic mutations. Genetic confirmation is required for POMC/PCSK1/LEPR (not required for Bardet-Biedl). This is not a drug for patients with typical obesity — referral to genetics is appropriate when considering this agent."
},
{
  name:"Metreleptin", brand:"Myalept",
  approval:"long", route:"injectable", tags:["mono"],
  wl:null,
  mechShort:"Recombinant leptin analog (replacement therapy)",
  dose:"Men >40 kg: Start 2.5 mg SC daily → increase by 1.25–2.5 mg/day to max 10 mg/day. Women >40 kg: Start 5 mg SC daily → increase to max 10 mg/day. Dose based on weight — see prescribing info for patients ≤40 kg.",
  indications:"ONLY for generalized lipodystrophy (congenital or acquired) as replacement therapy for leptin deficiency. NOT for partial lipodystrophy, NASH, HIV lipodystrophy, or general obesity.",
  contraindications:["Hypersensitivity to metreleptin or components","General obesity not associated with congenital leptin deficiency"],
  preScreen:["Confirm diagnosis of generalized lipodystrophy (congenital or acquired)","Assess for significant hematologic abnormalities — T-cell lymphoma risk","History of autoimmune disease (metreleptin may worsen autoimmune conditions)","Baseline blood glucose — hypoglycemia management plan if on insulin","Baseline lipid panel (lipodystrophy often has severe hypertriglyceridemia)","Review narrow therapeutic index medications (CYP450 effects possible)"],
  sideEffects:["Headache","Hypoglycemia (significant — especially in patients on insulin)","Decreased weight","Abdominal pain"],
  warnings:["T-cell lymphoma — carefully weigh benefits and risks in patients with significant hematologic abnormalities or acquired generalized lipodystrophy","Hypoglycemia — may require large dose reductions in insulin (drastic reductions sometimes needed)","Autoimmune disease progression — reported in treated patients","Hypersensitivity reactions (urticaria, generalized rash) — discontinue if occurs","Anti-metreleptin antibodies can develop and may neutralize the drug's activity"],
  interactions:["May alter CYP450 enzyme activity — important for oral contraceptives and drugs with narrow therapeutic index","Monitor narrow therapeutic index drugs closely after starting"],
  monitoring:["Blood glucose frequently — especially in first weeks if patient is on insulin","Lipid panel (triglycerides especially)","CBC for hematologic changes","Autoimmune markers if relevant","Anti-metreleptin antibody levels if efficacy loss is suspected"],
  specialNotes:"NOT a weight loss drug in the traditional sense — this is leptin replacement therapy for a specific rare disease (generalized lipodystrophy). Included here for completeness. Managing insulin doses is the most critical safety issue — dramatic insulin reductions (sometimes >50%) may be needed rapidly after starting. Requires REMS program enrollment."
}
];
